### ISSUE TITLE
Templates written in pug result in one root element warning

### ISSUE THREAD

**Issue by a0js** [vuejs/vue-loader#466]
After upgrading to 9.9.1, I started getting errors one pug templates.  The templates had only one root element but failed compiling with the error that component templates should have only one root element.

**Comment by k55k32** [comment]
yep I got the same error.

**Comment by cxr29** [comment]
+1

**Comment by thorning** [comment]
this is related to #464 and 09aa250645184ffc23e382c588992cd359080949 . Reverting the template part of the commit solves the issue for me, but maybe breaks other template languages?

**Comment by cho-is** [comment]
this is also happening for me

**Comment by riovir** [comment]
Mea culpa on breaking the template. It was not strictly necessary to add the -loader in that case. Was a misguided attempt at consistency on my part in 09aa250 in an attempt to fix #464.

**Comment by yyx990803** [comment]
should be fixed in 9.9.2

**Comment by solidevolution** [comment]
When it's available as release via npm?

**Comment by yyx990803** [comment]
@solidevolution it's already out.

**Comment by solidevolution** [comment]
I saw it on the master but there is no release/tag?!

**Comment by codysherman** [comment]
Hey just reporting in that I'm still experiencing this is 9.9.5.
